### ISSUE TITLE
Remarques

### ISSUE THREAD

**Issue by touhami** [sveyret/LaTeX#1]
Bonjour Monsieur,
Voici quelques remarques (je ne sais pas si je vais modifier ce file pour ajouter d'autres remarques ou créer d'autres, nous allons voir)

- il n'est pas recommandé d'imposer l'encodage.
```
\RequirePackage[utf8]{inputenc}
\RequirePackage[T1]{fontenc}
```

- de même pour la police `\RequirePackage{lmodern}`

-  `\LoadClass[twoside]{book}` est équivalent à `\LoadClass{book}`

**Comment by touhami** [comment]
`\def\@auteur{\null}` et ... à remplacer par `\def\@auteur{\@empty}` ou  `\let\@auteur\@empty`

Vous pouvez remplacer toutes les occurrences de `{\null}` par `{\@empty}`

**Comment by sveyret** [comment]
Imposer l'encodage et la police me permet de toujours présenter mes livres de la même façon sans avoir à me reposer la questions, plusieurs années plus tard, lorsque je décide d'en écrire un nouveau. Je ne vais donc pas modifier cela…
Merci pour les autres infos, la nouvelle version avec les corrections devrait arriver dans les minutes qui viennent. :smile:

**Comment by touhami** [comment]
Bonjour Monsieur.
Voici deux remarques.

- `\par\par`  est équivalent à `\par`

- le code suivant
```
\ifbrouillon
  \renewcommand\chapter{%
    \thispagestyle{plain}%
    \global\@topnum\z@%
    \@afterindentfalse%
    \secdef\@chapter\@schapter%
  }
\fi
```
à remplacer par 

```
\ifbrouillon
  \renewcommand\chapter{%
    \par
    \thispagestyle{plain}%
    \@afterindentfalse%
    \secdef\@chapter\@schapter%
  }
\fi
```
d’ailleurs je ne suis pas sûr si vous avez vraiment besoin d'utiliser `\thispagestyle{plain}`

**Comment by sveyret** [comment]
Merci, les modifications ont été apportées…
